import Post from './models/post';

export default function createFakeData() {
  const posts = [...Array(40).keys()].map((i) => ({
    title: `포스트#${i}`,
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at felis tortor. Nulla eu velit in neque fringilla efficitur. Donec viverra nisl sed velit faucibus, eu tempus eros tristique. Vestibulum vestibulum metus ipsum, eget vehicula erat sagittis efficitur. Maecenas quis ornare mauris. Sed purus enim, mattis eget turpis in, fringilla ornare enim. Duis rutrum lacus felis, in cursus dolor egestas egestas. Aliquam at euismod augue. Aliquam laoreet vestibulum magna, consequat convallis velit egestas a. Vivamus ut lorem pharetra, egestas mauris eu, dapibus nisi. Sed id sapien placerat, congue velit vel, aliquam turpis. Nunc at eleifend leo, nec vehicula leo. Nullam feugiat nunc vel mi auctor pharetra. Nullam vulputate accumsan orci, vel semper purus finibus a. Duis ultrices rhoncus massa, vel ullamcorper lorem aliquet ac. Praesent scelerisque eros vel metus lobortis, ac varius tellus egestas. Etiam dictum lobortis eleifend. Nam fermentum ante porta arcu vestibulum, ac faucibus lectus venenatis. Aliquam eu pulvinar justo, ac euismod diam. Praesent tempor turpis lectus, quis tempor turpis dictum sit amet. Donec eros mi, condimentum id maximus vel, fringilla vitae sem. Aenean sit amet neque ut ipsum faucibus convallis.Ut viverra id dolor sed scelerisque. Pellentesque lobortis, libero et tincidunt rhoncus, sapien elit cursus enim, a pretium diam urna in dolor. Aenean sed nisi quis odio interdum commodo. Ut posuere, mauris sit amet gravida luctus, diam tortor suscipit lectus, quis aliquam nulla risus sit amet nunc. Nunc pulvinar sem in magna cursus, et ullamcorper mi pulvinar. Cras pellentesque est quis laoreet euismod. Donec sagittis sem nec pellentesque condimentum. Sed maximus mollis luctus. Phasellus fermentum felis sit amet augue blandit gravida. Donec fermentum ipsum sed leo vestibulum finibus. Nunc non leo non quam volutpat vestibulum ut quis tortor. Suspendisse ut justo id urna elementum sollicitudin id sit amet mi. Proin tempus odio egestas pulvinar dictum. Aliquam nisi eros, porttitor in augue vitae, accumsan tempus nisl. In accumsan faucibus dignissim. Donec nec posuere velit, in posuere urna.Quisque sapien tortor, sodales id enim a, tristique dictum arcu. Suspendisse rutrum felis vel odio laoreet maximus. Nullam dignissim mattis erat quis lobortis. Nunc tincidunt ultrices lobortis. Sed fermentum placerat urna, id eleifend ante eleifend et. Vivamus convallis maximus arcu in sollicitudin. Suspendisse egestas neque sed placerat cursus. Maecenas mattis tincidunt erat nec volutpat. Maecenas bibendum tellus est, ut facilisis massa euismod quis. Vivamus ultrices nulla justo, sed euismod nulla ultrices ac. Donec non ante placerat risus egestas consequat. Vivamus vitae',
    tags: ['가짜', '데이터'],
  }));

  Post.insertMany(posts, (err, docs) => {
    console.log(docs);
  });
}
